// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.30.2
// source: scripts/mlservice.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnalyzeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageData     []byte                 `protobuf:"bytes,1,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeRequest) Reset() {
	*x = AnalyzeRequest{}
	mi := &file_scripts_mlservice_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeRequest) ProtoMessage() {}

func (x *AnalyzeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_scripts_mlservice_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeRequest) Descriptor() ([]byte, []int) {
	return file_scripts_mlservice_proto_rawDescGZIP(), []int{0}
}

func (x *AnalyzeRequest) GetImageData() []byte {
	if x != nil {
		return x.ImageData
	}
	return nil
}

func (x *AnalyzeRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *AnalyzeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type AnalyzeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Condition     string                 `protobuf:"bytes,2,opt,name=condition,proto3" json:"condition,omitempty"`
	Confidence    int32                  `protobuf:"varint,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	Issues        []*CarIssue            `protobuf:"bytes,5,rep,name=issues,proto3" json:"issues,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeResponse) Reset() {
	*x = AnalyzeResponse{}
	mi := &file_scripts_mlservice_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeResponse) ProtoMessage() {}

func (x *AnalyzeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_scripts_mlservice_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeResponse) Descriptor() ([]byte, []int) {
	return file_scripts_mlservice_proto_rawDescGZIP(), []int{1}
}

func (x *AnalyzeResponse) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *AnalyzeResponse) GetCondition() string {
	if x != nil {
		return x.Condition
	}
	return ""
}

func (x *AnalyzeResponse) GetConfidence() int32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *AnalyzeResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AnalyzeResponse) GetIssues() []*CarIssue {
	if x != nil {
		return x.Issues
	}
	return nil
}

type CarIssue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Location      string                 `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	Severity      int32                  `protobuf:"varint,3,opt,name=severity,proto3" json:"severity,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CarIssue) Reset() {
	*x = CarIssue{}
	mi := &file_scripts_mlservice_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CarIssue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarIssue) ProtoMessage() {}

func (x *CarIssue) ProtoReflect() protoreflect.Message {
	mi := &file_scripts_mlservice_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CarIssue.ProtoReflect.Descriptor instead.
func (*CarIssue) Descriptor() ([]byte, []int) {
	return file_scripts_mlservice_proto_rawDescGZIP(), []int{2}
}

func (x *CarIssue) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CarIssue) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *CarIssue) GetSeverity() int32 {
	if x != nil {
		return x.Severity
	}
	return 0
}

func (x *CarIssue) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_scripts_mlservice_proto protoreflect.FileDescriptor

const file_scripts_mlservice_proto_rawDesc = "" +
	"\n" +
	"\x17scripts/mlservice.proto\x12\vcaranalysis\"d\n" +
	"\x0eAnalyzeRequest\x12\x1d\n" +
	"\n" +
	"image_data\x18\x01 \x01(\fR\timageData\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\"\xb4\x01\n" +
	"\x0fAnalyzeResponse\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x1c\n" +
	"\tcondition\x18\x02 \x01(\tR\tcondition\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x05R\n" +
	"confidence\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12-\n" +
	"\x06issues\x18\x05 \x03(\v2\x15.caranalysis.CarIssueR\x06issues\"x\n" +
	"\bCarIssue\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1a\n" +
	"\blocation\x18\x02 \x01(\tR\blocation\x12\x1a\n" +
	"\bseverity\x18\x03 \x01(\x05R\bseverity\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription2V\n" +
	"\vCarAnalysis\x12G\n" +
	"\n" +
	"AnalyzeCar\x12\x1b.caranalysis.AnalyzeRequest\x1a\x1c.caranalysis.AnalyzeResponseB\x06Z\x04./pbb\x06proto3"

var (
	file_scripts_mlservice_proto_rawDescOnce sync.Once
	file_scripts_mlservice_proto_rawDescData []byte
)

func file_scripts_mlservice_proto_rawDescGZIP() []byte {
	file_scripts_mlservice_proto_rawDescOnce.Do(func() {
		file_scripts_mlservice_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scripts_mlservice_proto_rawDesc), len(file_scripts_mlservice_proto_rawDesc)))
	})
	return file_scripts_mlservice_proto_rawDescData
}

var file_scripts_mlservice_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_scripts_mlservice_proto_goTypes = []any{
	(*AnalyzeRequest)(nil),  // 0: caranalysis.AnalyzeRequest
	(*AnalyzeResponse)(nil), // 1: caranalysis.AnalyzeResponse
	(*CarIssue)(nil),        // 2: caranalysis.CarIssue
}
var file_scripts_mlservice_proto_depIdxs = []int32{
	2, // 0: caranalysis.AnalyzeResponse.issues:type_name -> caranalysis.CarIssue
	0, // 1: caranalysis.CarAnalysis.AnalyzeCar:input_type -> caranalysis.AnalyzeRequest
	1, // 2: caranalysis.CarAnalysis.AnalyzeCar:output_type -> caranalysis.AnalyzeResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_scripts_mlservice_proto_init() }
func file_scripts_mlservice_proto_init() {
	if File_scripts_mlservice_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scripts_mlservice_proto_rawDesc), len(file_scripts_mlservice_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_scripts_mlservice_proto_goTypes,
		DependencyIndexes: file_scripts_mlservice_proto_depIdxs,
		MessageInfos:      file_scripts_mlservice_proto_msgTypes,
	}.Build()
	File_scripts_mlservice_proto = out.File
	file_scripts_mlservice_proto_goTypes = nil
	file_scripts_mlservice_proto_depIdxs = nil
}
