// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: scripts/mlservice.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CarAnalysis_AnalyzeCar_FullMethodName = "/caranalysis.CarAnalysis/AnalyzeCar"
)

// CarAnalysisClient is the client API for CarAnalysis service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CarAnalysisClient interface {
	AnalyzeCar(ctx context.Context, in *AnalyzeRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error)
}

type carAnalysisClient struct {
	cc grpc.ClientConnInterface
}

func NewCarAnalysisClient(cc grpc.ClientConnInterface) CarAnalysisClient {
	return &carAnalysisClient{cc}
}

func (c *carAnalysisClient) AnalyzeCar(ctx context.Context, in *AnalyzeRequest, opts ...grpc.CallOption) (*AnalyzeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeResponse)
	err := c.cc.Invoke(ctx, CarAnalysis_AnalyzeCar_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CarAnalysisServer is the server API for CarAnalysis service.
// All implementations must embed UnimplementedCarAnalysisServer
// for forward compatibility.
type CarAnalysisServer interface {
	AnalyzeCar(context.Context, *AnalyzeRequest) (*AnalyzeResponse, error)
	mustEmbedUnimplementedCarAnalysisServer()
}

// UnimplementedCarAnalysisServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCarAnalysisServer struct{}

func (UnimplementedCarAnalysisServer) AnalyzeCar(context.Context, *AnalyzeRequest) (*AnalyzeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AnalyzeCar not implemented")
}
func (UnimplementedCarAnalysisServer) mustEmbedUnimplementedCarAnalysisServer() {}
func (UnimplementedCarAnalysisServer) testEmbeddedByValue()                     {}

// UnsafeCarAnalysisServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CarAnalysisServer will
// result in compilation errors.
type UnsafeCarAnalysisServer interface {
	mustEmbedUnimplementedCarAnalysisServer()
}

func RegisterCarAnalysisServer(s grpc.ServiceRegistrar, srv CarAnalysisServer) {
	// If the following call pancis, it indicates UnimplementedCarAnalysisServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CarAnalysis_ServiceDesc, srv)
}

func _CarAnalysis_AnalyzeCar_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CarAnalysisServer).AnalyzeCar(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CarAnalysis_AnalyzeCar_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CarAnalysisServer).AnalyzeCar(ctx, req.(*AnalyzeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CarAnalysis_ServiceDesc is the grpc.ServiceDesc for CarAnalysis service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CarAnalysis_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "caranalysis.CarAnalysis",
	HandlerType: (*CarAnalysisServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AnalyzeCar",
			Handler:    _CarAnalysis_AnalyzeCar_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "scripts/mlservice.proto",
}
